server.port=9090

spring.data.mongodb.uri=mongodb+srv://pujaojha7187:Kristyp21@cluster0.wiwtl6f.mongodb.net/import_export_db?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pujaojha7187@gmail.com
spring.mail.password=dfrhorbdrsrkbpch

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
